# Generated by Django 5.1.7 on 2025-04-26 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_rename_firstname_users_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='FirstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='LastName',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='taskinformation',
            name='AssignedBy',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Email',
        ),
        migrations.AlterField(
            model_name='comments',
            name='TaskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.taskinformation'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Management.users'),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='AssignedID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='AssignedTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assigned', to='Management.users'),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='TaskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.taskinformation'),
        ),
        migrations.AlterField(
            model_name='taskinformation',
            name='TaskID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(max_length=16),
        ),
        migrations.AddField(
            model_name='taskinformation',
            name='Assignedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
