# Generated by Django 5.1.3 on 2025-02-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_personalinfo_companylogo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ecgPatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientId', models.CharField(max_length=50, null=True)),
                ('PatientName', models.CharField(max_length=70, null=True)),
                ('age', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('testdate', models.CharField(max_length=50, null=True)),
                ('reportdate', models.CharField(max_length=50, null=True)),
                ('heartrate', models.CharField(max_length=50, null=True)),
                ('findings', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xrayPatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientId', models.CharField(max_length=50, null=True)),
                ('PatientName', models.CharField(max_length=70, null=True)),
                ('age', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('testdate', models.CharField(max_length=50, null=True)),
                ('reportdate', models.CharField(max_length=50, null=True)),
                ('impressions', models.CharField(max_length=100, null=True)),
                ('findings', models.CharField(max_length=200, null=True)),
                ('jpeg_file', models.ImageField(upload_to='jpeg_files/')),
            ],
        ),
    ]
