# Generated by Django 5.1.3 on 2025-07-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_category_id_alter_comment_id_alter_tickets_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('Open', 'open'), ('Pending', 'pending'), ('Resolved', 'Resolved'), ('Closed', 'closed')], default='Open', max_length=100),
        ),
    ]
